import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        <div className="flex h-screen w-full">
          <Sidebar />
        <div className="flex ml-64 w-full h-full flex-col p-[100px] rounded-xl">
          {children}
        </div>
        </div>
        </body>
    </html>
  );
}
